### ISSUE TITLE
System scope tasks seem to have problems when XDG_RUNTIME_DIR is set

### ISSUE THREAD

**Issue by mhjacks** [linux-system-roles/systemd#72]
I ran into some problems with synthesized host records in systemd-resolved, and was using this collection to inject dropins.

Using the latest version, I see consistent hangs at this point:

```
TASK [fedora.linux_system_roles.systemd : Reload systemd] ******************************************
task path: /home/mjackson/.ansible/collections/ansible_collections/fedora/linux_system_roles/roles/systemd/tasks/main.yml:106
<srv-f41-t3.imladris.lan> ESTABLISH SSH CONNECTION FOR USER: None
<srv-f41-t3.imladris.lan> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/mjackson/.ansible/cp/bcb77c72d4"' srv-f41-t3.imladris.lan '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<srv-f41-t3.imladris.lan> (0, b'/home/mjackson\n', b'')
<srv-f41-t3.imladris.lan> ESTABLISH SSH CONNECTION FOR USER: None
<srv-f41-t3.imladris.lan> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/mjackson/.ansible/cp/bcb77c72d4"' srv-f41-t3.imladris.lan '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/mjackson/.ansible/tmp `"&& mkdir "` echo /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742 `" && echo ansible-tmp-1733538959.9283075-90102-130389421889742="` echo /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742 `" ) && sleep 0'"'"''
<srv-f41-t3.imladris.lan> (0, b'ansible-tmp-1733538959.9283075-90102-130389421889742=/home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742\n', b'')
Using module file /usr/lib/python3.13/site-packages/ansible/modules/systemd.py
<srv-f41-t3.imladris.lan> PUT /home/mjackson/.ansible/tmp/ansible-local-898670xmituke/tmpjv3ozbn2 TO /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742/AnsiballZ_systemd.py
<srv-f41-t3.imladris.lan> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/mjackson/.ansible/cp/bcb77c72d4"' '[srv-f41-t3.imladris.lan]'
<srv-f41-t3.imladris.lan> (0, b'sftp> put /home/mjackson/.ansible/tmp/ansible-local-898670xmituke/tmpjv3ozbn2 /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742/AnsiballZ_systemd.py\n', b'')
<srv-f41-t3.imladris.lan> ESTABLISH SSH CONNECTION FOR USER: None
<srv-f41-t3.imladris.lan> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/mjackson/.ansible/cp/bcb77c72d4"' srv-f41-t3.imladris.lan '/bin/sh -c '"'"'chmod u+x /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742/ /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742/AnsiballZ_systemd.py && sleep 0'"'"''
<srv-f41-t3.imladris.lan> (0, b'', b'')
<srv-f41-t3.imladris.lan> ESTABLISH SSH CONNECTION FOR USER: None
<srv-f41-t3.imladris.lan> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/mjackson/.ansible/cp/bcb77c72d4"' -tt srv-f41-t3.imladris.lan '/bin/sh -c '"'"'/usr/bin/python3 /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742/AnsiballZ_systemd.py && sleep 0'"'"''
<srv-f41-t3.imladris.lan> (1, b'\x1b[1;31m==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ====\r\n\x1b[0mAuthentication is required to reload the systemd state.\r\nMultiple identities can be used for authentication:\r\n 1.  Local Admin (localadmin)\r\n 2.  Martin Jackson (mjackson)\r\nChoose identity to authenticate as (1-2): \r\n{"failed": true, "msg": "failure 1 during daemon-reload: Reload daemon failed: Method call timed out\\n", "invocation": {"module_args": {"daemon_reload": true, "scope": "system", "daemon_reexec": false, "no_block": false, "name": null, "state": null, "enabled": null, "force": null, "masked": null}}}\r\n', b'Shared connection to srv-f41-t3.imladris.lan closed.\r\n')
<srv-f41-t3.imladris.lan> Failed to connect to the host via ssh: Shared connection to srv-f41-t3.imladris.lan closed.
<srv-f41-t3.imladris.lan> ESTABLISH SSH CONNECTION FOR USER: None
<srv-f41-t3.imladris.lan> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/mjackson/.ansible/cp/bcb77c72d4"' srv-f41-t3.imladris.lan '/bin/sh -c '"'"'rm -f -r /home/mjackson/.ansible/tmp/ansible-tmp-1733538959.9283075-90102-130389421889742/ > /dev/null 2>&1 && sleep 0'"'"''
<srv-f41-t3.imladris.lan> (0, b'', b'')
failed: [srv-f41-t3.imladris.lan] (item=root) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reexec": false,
            "daemon_reload": true,
            "enabled": null,
            "force": null,
            "masked": null,
            "name": null,
            "no_block": false,
            "scope": "system",
            "state": null
        }
    },
    "item": "root",
    "msg": "failure 1 during daemon-reload: Reload daemon failed: Method call timed out\n"
}

PLAY RECAP *****************************************************************************************
srv-f41-t3.imladris.lan    : ok=18   changed=2    unreachable=0    failed=1    skipped=27   rescued=0    ignored=0
```

These things seem not to happen when XDG_RUNTIME_DIR is not set. (I'm not sure that's the problem, but it kind of looks like that).

Here are the playbook and template I was running: (the unit reload at the end works fine without the extra env var setting):

```yaml
---
- name: Test playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Fix systemd-resolved if needed
      become: true
      when:
        - ansible_facts['services']['systemd-resolved.service']['status'] is defined
        - ansible_facts['services']['systemd-resolved.service']['status'] == "enabled"
      block:
        - name: Manage systemd for systemd-resolved
          ansible.builtin.include_role:
            name: fedora.linux_system_roles.systemd
          vars:
            systemd_dropins:
              - systemd-resolved.service.conf.j2

        - name: Bounce systemd-resolved
          ansible.builtin.systemd:
            daemon_reload: true
          when: dropin_stat is changed

        - name: Bounce systemd-resolved
          ansible.builtin.service:
            name: systemd-resolved
            state: restarted
          when: dropin_stat is changed
```

And the template:
```
[Service]
Environment=SYSTEMD_RESOLVED_SYNTHESIZE_HOSTNAME=0
```
